In [171]:
%config IPCompleter.greedy=True

In [172]:
import pandas as pd
import numpy as np

In [173]:
dataset=pd.read_csv("Social_Network_Ads.csv")
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [174]:
X=dataset.iloc[:,1:4].values
print(X)

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]


In [175]:
y=dataset.iloc[:,-1].values
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [176]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])], remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 19 19000]
 [0.0 1.0 35 20000]
 [1.0 0.0 26 43000]
 ...
 [1.0 0.0 50 20000]
 [0.0 1.0 36 33000]
 [1.0 0.0 49 36000]]


In [177]:
from sklearn.preprocessing import MinMaxScaler
norm=MinMaxScaler()
X=norm.fit_transform(X)
print(X)

[[0.         1.         0.02380952 0.02962963]
 [0.         1.         0.4047619  0.03703704]
 [1.         0.         0.19047619 0.20740741]
 ...
 [1.         0.         0.76190476 0.03703704]
 [0.         1.         0.42857143 0.13333333]
 [1.         0.         0.73809524 0.15555556]]


In [178]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=0)
print(X_test)

[[0.         1.         0.28571429 0.53333333]
 [1.         0.         0.47619048 0.25925926]
 [0.         1.         0.4047619  0.44444444]
 [1.         0.         0.28571429 0.47407407]
 [1.         0.         0.4047619  0.25925926]
 [0.         1.         0.21428571 0.03703704]
 [1.         0.         0.30952381 0.        ]
 [0.         1.         0.42857143 0.95555556]
 [1.         0.         0.         0.39259259]
 [0.         1.         0.69047619 0.20740741]
 [0.         1.         0.28571429 0.25185185]
 [1.         0.         0.23809524 0.2962963 ]
 [0.         1.         0.45238095 0.2962963 ]
 [0.         1.         0.5        0.45925926]
 [0.         1.         0.04761905 0.52592593]
 [1.         0.         0.33333333 0.75555556]
 [0.         1.         0.45238095 0.45925926]
 [0.         1.         0.02380952 0.51851852]
 [1.         0.         0.88095238 0.85185185]
 [0.         1.         0.4047619  0.05185185]
 [1.         0.         0.4047619  0.23703704]
 [1.         

In [179]:
from sklearn.ensemble import RandomForestRegressor
regression=RandomForestRegressor(n_estimators=40)
regression.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=40, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [180]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [181]:
y_pred=regression.predict(X_test)
print(y_pred)

[0.    0.    0.    0.    0.    0.    0.    1.    0.    0.625 0.    0.
 0.175 0.25  0.    0.875 0.325 0.    0.975 0.    0.    0.675 0.    0.975
 0.    0.575 0.    0.    0.175 0.    0.    0.225 0.9   0.175 0.    0.
 0.    0.    0.    1.    0.    0.    0.    0.    0.4   0.    0.125 0.725
 0.    0.95  0.975 0.    0.    0.675 0.6   0.95  0.    0.    1.    0.
 0.    0.825 0.    1.    0.    0.65  0.    0.    0.    0.425 1.    0.075
 0.    0.85  0.    0.    0.525 0.    1.    0.9  ]


In [182]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7470611285266457

In [183]:
from sklearn.neighbors import KNeighborsClassifier
neighbour=KNeighborsClassifier(n_neighbors=11,metric="minkowski",p=2)
neighbour.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [184]:
y_pred1=neighbour.predict(X_test)
print(y_pred1)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [185]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred1)
acc=accuracy_score(y_test,y_pred1)
print(acc)
print(cm)

0.95
[[55  3]
 [ 1 21]]
