In [95]:
%config IPCompleter.greedy=True

In [96]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

In [97]:
dataset=pd.read_csv("Social_Network_Ads.csv")
X=dataset.iloc[:,2:4].values
y=dataset.iloc[:,4].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
neighbour=KNeighborsClassifier(n_neighbors=11,metric="minkowski",p=2)
neighbour.fit(X_train,y_train)
y_pred=neighbour.predict(X_test)
print(y_pred)

from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
[[55  3]
 [ 1 21]]
0.95


In [98]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
y_pred1=tree.predict(X_test)
print(y_pred1)

from sklearn.metrics import accuracy_score, confusion_matrix
cm1=confusion_matrix(y_test,y_pred1)
print(cm1)
acc1=accuracy_score(y_test,y_pred1)
print(acc1)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1
 1 0 0 0 1 1]
[[53  5]
 [ 2 20]]
0.9125


In [99]:
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(X_train,y_train)
y_pred2=naive.predict(X_test)
print(y_pred2)

from sklearn.metrics import confusion_matrix, accuracy_score
acc2=accuracy_score(y_test,y_pred2)
print(acc2)
cm2=confusion_matrix(y_test,y_pred2)
print(cm2)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 1 0 1 1]
0.9375
[[54  4]
 [ 1 21]]


In [100]:
from sklearn.svm import SVC
classi=SVC(kernel='linear')
classi.fit(X_train,y_train)
y_pred3=classi.predict(X_test)
print(y_pred3)

from sklearn.metrics import accuracy_score, confusion_matrix
cm3=confusion_matrix(y_test,y_pred3)
print(cm3)
acc3=accuracy_score(y_test,y_pred3)
print(acc3)

[0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0
 0 0 1 0 1 1]
[[52  6]
 [ 3 19]]
0.8875


In [101]:
from sklearn.ensemble import RandomForestClassifier
forest_regressor=RandomForestClassifier(n_estimators=50)
forest_regressor.fit(X_train,y_train)
y_pred4=forest_regressor.predict(X_test)
print(y_pred4)

from sklearn.metrics import accuracy_score, confusion_matrix
cm4=confusion_matrix(y_test,y_pred4)
print(cm4)
acc4=accuracy_score(y_test,y_pred4)
print(acc4)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 1
 1 0 0 0 1 1]
[[53  5]
 [ 2 20]]
0.9125
